### ISSUE TITLE
PrivateSend Official Documentation 404

### ISSUE THREAD

**Issue by PastaPastaPasta** [dash-docs/dash-docs#154]
https://dash-docs.github.io/en/developer-guide#privatesend 

"Official Documentation PrivateSend page." link points to a 404

Source File: _includes/devdoc/guide_dash_features.md

**Comment by thephez** [comment]
Good find. Thanks for reporting. The structure of docs.dash.org changed at some point so `stable` is used instead of `latest` (i.e. https://docs.dash.org/en/latest/introduction/features.html#privatesend). There are several other links that are broken as well.
